library(dplyr)
library(purrr)

# For a grid of params, return list of model predictions.
grid_predict <- function(recipe, split, param_grid, target, train_predict){
  foreach(params = param_grid) %do% {
    train_predict(recipe, split, params, target)
  }
}


# df is expected to have columns `recipes` and `splits`
# param_gris is expected to be a list of list (generated by purrr::cross for example)
# train_predict is a function that takes parameters recipe, split, params and target, and returns
# model predictions using specified params.
# metrics is a list of metric functions, taking predictions and target values as parameters.
grid_search <- function(df, target, param_grid, train_predict, metrics){
  df %>%
    mutate(
      params = list(param_grid),
      pred = pmap(
        list(recipes, splits, params),
        tune,
        train_predict = train_predict_ranger,
        target = target
      )
    ) %>%
    unnest(params, pred) %$%
    bind_cols(
      .,
      map_dfr(
        pred,
        function(pred){
          invoke_map_dfc(
            metrics,
            list(list(pred))
          )
        }
      )
    ) %>%
    bind_cols(
      transpose(.$params) %>% map(unlist) %>% as_data_frame()
    ) %>% 
    select(-params)
}